version: '3.4'

services:
  remote-debug-sample:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80\
    ports:
      - "5155:80"
    # enable local OS code watching and hot deployment 
    # volumes:
    #   - ./remote-debug-sample:/src/remote-debug-sample
