version: '3.4'

services:
  remote-debug-sample:
    image: ${REGISTRY:-kiwiho}/remote-debug-sample:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: remote-debug-sample/Dockerfile.develop
  catelog-api:
    image: ${REGISTRY:-kiwiho}/catelog-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: kiwiho.example.Catelog.API/Dockerfile.develop
  basket-api:
    image: ${REGISTRY:-kiwiho}/basket-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: kiwiho.example.Basket.API/Dockerfile.develop

